### ISSUE TITLE
tiffile not found

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#494] opened 2023-11-01 23:03 UTC
Seen when watching Vincent, I saw a "ModuleNotFoundError" for the tiffile package when he was trying to use one of the Bruker Interfaces. It looks like tiffile is not installed correctly

**Comment by CodyCBakerPhD** [comment] 2023-11-06 20:03
Duplicate of #421

**Closed by CodyCBakerPhD** 2023-11-06 20:03 UTC
