### ISSUE TITLE
Error with paths when uploading to DANDI

### ISSUE THREAD

**Issue by iezqrom** [NeurodataWithoutBorders/nwb-guide#696] opened 2024-03-22 21:11 UTC
### Describe the issue

I'm trying to upload to DANDI and I'm getting the following error, which I don't know how to resolve:

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/42712006/e2377b8e-eac4-4af7-9cb2-72c48b592d3e)

It might be related to the warning below? I don't know how to set a relative path through the GUI though

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/42712006/650ed3fd-b537-41af-abcb-583aff73dde6)

### Steps to Reproduce

1. Create a new conversation pipeline
2. Manually set data and paths (Video - VideoInterface format)
3. Get some warnings but get through
4. Try to upload and fails

### Operating System

Ubuntu 20.04.6 LTS

### GUIDE Version

linux-latest

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment] 2024-03-22 21:30
duplicate of https://github.com/NeurodataWithoutBorders/nwb-guide/issues/608

external video files are a little tricky to handle during DANDI upload and we haven't added support for this in the GUIDE just yet

see https://github.com/NeurodataWithoutBorders/nwb-guide/issues/608#issuecomment-1936099394 for instructions on how to do a manual upload

**Closed** 2024-06-03 19:24 UTC
